# Generated by Django 5.2.7 on 2026-05-06 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crimerecord',
            options={},
        ),
        migrations.RemoveField(
            model_name='crimerecord',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='crimerecord',
            name='crime_type',
            field=models.CharField(choices=[('theft', 'Theft'), ('assault', 'Assault'), ('robbery', 'Robbery'), ('murder', 'Murder'), ('fraud', 'Fraud'), ('vandalism', 'Vandalism'), ('drug_offense', 'Drug Offense'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='crimerecord',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='crimerecord',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='crimerecord',
            name='location_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='crimerecord',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
