# Generated by Django 4.2.7 on 2026-05-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimes', '0002_alter_crimerecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimerecord',
            name='admin_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='proofs/'),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
